version: '3.8'

services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=default_password
      - MYSQL_DATABASE=checkpoint
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - checkpoint

  indexer:
    build: .
    networks:
      - checkpoint
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=mysql://root:default_password@mysql:3306/checkpoint
    depends_on:
      - mysql

  nginx:
    image: valian/docker-nginx-auto-ssl
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl_data:/etc/resty-auto-ssl
    environment:
      ALLOWED_DOMAINS: 'indexer.starkmint.com'
      SITES: 'indexer.starkmint.com=indexer:3000'
    networks:
      - checkpoint
    depends_on:
      - indexer


volumes:
  mysql:
    driver: local
  ssl_data:

networks:
  checkpoint:
    driver: bridge
