version: '3.8'

services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=default_password
      - MYSQL_DATABASE=checkpoint
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - checkpoint

  indexer:
    build: ./checkpoint_indexor
    networks:
      - checkpoint
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=mysql://root:default_password@mysql:3306/checkpoint

volumes:
  mysql:
    driver: local

networks:
  checkpoint:
    driver: bridge
