[package]
name = "starknet_forge_template"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[[target.starknet-contract]]
sierra = true
casm = true

[dependencies]
starknet = "2.3.0"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.10.1" }
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.8.0-beta.0" }

[tool.snforge]
# exit_first = true

[tool.sncast]
account = "test1"
accounts-file = "/Users/pierre-etienne/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://localhost:5050/rpc"


[tool.sncast.test5]
account = "test5"
accounts-file = "/Users/pierre-etienne/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://localhost:5050/rpc"

#[tool.sncast]
#account = "testnet"
#accounts-file = "/Users/pierre-etienne/.starknet_accounts/starknet_open_zeppelin_accounts.json"
#url = "https://starknet-goerli.infura.io/v3/3d5e774ac52847fd8cf5c2dd2fc76cf6"
